import pytest

from src.gros_client.robot import Robot


class TestYourClass:
    @pytest.fixture
    def robot_instance(self):
        return Robot()

    def test_get_states(self, robot_instance):
        ...
        # Test the get_states method
        # ...

    def test_get_type(self, robot_instance):
        ...
        # Test the get_type method
        # ...

    def test_get_video_status(self, robot_instance):
        ...
        # Test the get_video_status method
        # ...

    def test_get_video_stream_url(self, robot_instance):
        ...
        # Test the get_video_stream_url method
        # ...

    def test_set_mode(self, robot_instance):
        ...
        # Test the set_mode method
        # ...

    def test_get_joint_limit(self, robot_instance):
        ...
        # Test the get_joint_limit method
        # ...

    def test_get_joint_states(self, robot_instance):
        ...
        # Test the get_joint_states method
        # ...

    def test_enable_debug_state(self, robot_instance):
        ...
        # Test the enable_debug_state method
        # ...

    def test_stand(self, robot_instance):
        ...
        # Test the stand method
        # ...

    def test_move(self, robot_instance):
        ...
        # Test the move method
        # ...

    def test_head(self, robot_instance):
        ...
        # Test the head method
        # ...

    def test_close_websocket(self, robot_instance):
        ...